[package]

name = "hash_ring"
version = "0.0.5"
authors = ["Matt McCoy <mattnenterprise@yahoo.com>"]
repository = "https://github.com/mattnenterprise/rust-hash-ring"
description = "consistent hashing library for Rust"
readme = "README.md"
license = "MIT"

[dependencies]
rust-crypto = "0.2.34"
