[package]

name = "hash_ring"
version = "0.0.5"
authors = ["Matt McCoy <mattnenterprise@yahoo.com>"]
documentation = "http://mattnenterprise.github.io/rust-hash-ring"
repository = "https://github.com/mattnenterprise/rust-hash-ring"
homepage = "https://github.com/mattnenterprise/rust-hash-ring"
description = "Consistent Hashing library for Rust"
readme = "README.md"
license = "MIT"

[dependencies]
rust-crypto = "0.2.34"
